/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SignInRouteImport } from "./routes/sign-in";
import { Route as AppRouteRouteImport } from "./routes/app/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AppConfigsIndexRouteImport } from "./routes/app/configs/index";
import { Route as AppConfigsNewRouteImport } from "./routes/app/configs/new";
import { Route as AppConfigsSlugRouteImport } from "./routes/app/configs/$slug";

const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const AppRouteRoute = AppRouteRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AppConfigsIndexRoute = AppConfigsIndexRouteImport.update({
  id: "/configs/",
  path: "/configs/",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppConfigsNewRoute = AppConfigsNewRouteImport.update({
  id: "/configs/new",
  path: "/configs/new",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppConfigsSlugRoute = AppConfigsSlugRouteImport.update({
  id: "/configs/$slug",
  path: "/configs/$slug",
  getParentRoute: () => AppRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/app": typeof AppRouteRouteWithChildren;
  "/sign-in": typeof SignInRoute;
  "/app/configs/$slug": typeof AppConfigsSlugRoute;
  "/app/configs/new": typeof AppConfigsNewRoute;
  "/app/configs/": typeof AppConfigsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/app": typeof AppRouteRouteWithChildren;
  "/sign-in": typeof SignInRoute;
  "/app/configs/$slug": typeof AppConfigsSlugRoute;
  "/app/configs/new": typeof AppConfigsNewRoute;
  "/app/configs": typeof AppConfigsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/app": typeof AppRouteRouteWithChildren;
  "/sign-in": typeof SignInRoute;
  "/app/configs/$slug": typeof AppConfigsSlugRoute;
  "/app/configs/new": typeof AppConfigsNewRoute;
  "/app/configs/": typeof AppConfigsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/app"
    | "/sign-in"
    | "/app/configs/$slug"
    | "/app/configs/new"
    | "/app/configs/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/app"
    | "/sign-in"
    | "/app/configs/$slug"
    | "/app/configs/new"
    | "/app/configs";
  id:
    | "__root__"
    | "/"
    | "/app"
    | "/sign-in"
    | "/app/configs/$slug"
    | "/app/configs/new"
    | "/app/configs/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppRouteRoute: typeof AppRouteRouteWithChildren;
  SignInRoute: typeof SignInRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sign-in": {
      id: "/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app": {
      id: "/app";
      path: "/app";
      fullPath: "/app";
      preLoaderRoute: typeof AppRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app/configs/": {
      id: "/app/configs/";
      path: "/configs";
      fullPath: "/app/configs/";
      preLoaderRoute: typeof AppConfigsIndexRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/app/configs/new": {
      id: "/app/configs/new";
      path: "/configs/new";
      fullPath: "/app/configs/new";
      preLoaderRoute: typeof AppConfigsNewRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/app/configs/$slug": {
      id: "/app/configs/$slug";
      path: "/configs/$slug";
      fullPath: "/app/configs/$slug";
      preLoaderRoute: typeof AppConfigsSlugRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
  }
}

interface AppRouteRouteChildren {
  AppConfigsSlugRoute: typeof AppConfigsSlugRoute;
  AppConfigsNewRoute: typeof AppConfigsNewRoute;
  AppConfigsIndexRoute: typeof AppConfigsIndexRoute;
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppConfigsSlugRoute: AppConfigsSlugRoute,
  AppConfigsNewRoute: AppConfigsNewRoute,
  AppConfigsIndexRoute: AppConfigsIndexRoute,
};

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  SignInRoute: SignInRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "../src/router.tsx";
import type { startInstance } from "../src/start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
